# -*- coding: utf-8 -*-
"""Pract3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npddNFr2r3bZE9GFO2TWLRbYkbr4m6X6
"""

def f(x):
  return (x+3)**2


def df(x):
  return 2*(x+3)

def gradient_descent(iterations,learning_rate,start_x):
  current_x=start_x
  for i in range (0,iterations):
    gradient=df(current_x)
    current_x=current_x-(learning_rate*gradient)
    print(f"x={i+1},cost={f(current_x)}")

  print(f"Nearest gradiant is {current_x:.4f}")
  return current_x

gradient_descent(20,0.1,2)